name: coffeebreak
channels:
    - conda-forge
dependencies:
    - python=3
    - numpy
    - scipy
    - matplotlib
    - pandas
    - seaborn
    - altair
    - jupyter
    - sympy
    - jupyter_contrib_nbextensions
    - attrs
    - rise
